### ISSUE TITLE
[Feature Request] Add 1080p to "Force Resolution".

### ISSUE THREAD

**Issue by kevinlekiller** [Mafrans/StadiaPlus#32]
When forcing VP9 and leaving the resolution "Automatic" on a display with the resolution set to 2160p, stadia will run at 2160p, to use 1080p with VP9, the display resolution needs to be changed to 1080p before starting the game.

Adding an option to force the stadia resolution to 1080p would avoid having to change the display resolution. (Some games will run at 30 fps when stadia is running at 2160p, and it's preferable to run the game at 1080p for the higher framerate.)

**Comment by sagz** [comment]
This is misguided. Client resolution to 1080p won't change the 60fps/30fps aspect. You have to go into Stadia settings and switch the 'Data Usage and Performance' to 'Balanced' instead of 'Best visual quality'.

If you have it set to 'Best visual quality' Stadia will always render the game assuming client can go upto 2160p if possible. To make it limit itself to 1080p, you have to switch that setting above.
