### ISSUE TITLE
Add SpeedTest tab into UI

### ISSUE THREAD

**Issue by Lordubuntu94** [Mafrans/StadiaPlus#37]
Hi again, i was wondering that could be cool to have a new tab linked in some way to the speedtest provided by google ( this one : https://projectstream.google.com/speedtest ).

Cheers!

**Comment by ELowry** [comment]
Important note here: unfortunately the speed test proposed by Google is not necessarily a good reflection of real world performance;

- I am fairly certain that the testing servers are not inside Google data centers. This means the data will not be as relevant as cross-referencing results from multiple speed testing sources would.
- Some key indicators of Stadia performance (ping, jitter, packet loss, etc.) are missing. These are much more critical to evaluating Stadia performance, though still not a guarantee (since low-end routers, device network hardware and decoding capabilities seem to be the bottleneck as often or more often than the actual network).

I would suggest looking for a good open-source type speed test; preferably one with with no user tracking and/or profiting from the data. For France, I have found that https://testdebit.info fits that profile well, though it is only reliable in and around France.

A possibility would be to simply include a page/pop-up/tab with instructions on how people should interpret the data (and emphasizing the fact that speed is absolutely not the most important value) with a list of possible sites to use for speed testing?
