### ISSUE TITLE
Automatic Language Selection doesn't follow OS/Chrome settings.

### ISSUE THREAD

**Issue by ELowry** [Mafrans/StadiaPlus#67]
**The context:**

- I have both my OS (Windows) and Chrome (+ Google account) set to "English (United States)" as my default language.
- I use a French keyboard layout by default.
- I live in France and have a french IP.

**The issue:**

The Stadia+ UI is partly displayed in French. I venture to guess that the "partly" is because not all strings have been translated.
In my case, having forced both the browser and OS languages, I would expect Stadia+ to display its UIs in English, not French.

**Note:**

I have just figured out this setting can be overridden, which is great. Though the "issue" could still be nice to fix some day... It's just probably not a priority.

**Comment by Mafrans** [comment]
This is intentional, as some versions of chrome will default to English even when Stadia itself is in a different language. Stadia+ will only automatically select English (US) if no other language is present in the language array.

I decided on this due to the fact many Stadia+ users are not native English speakers and defaulting to English may impair their ability to use the extension. If they prefer English they can always change it in the Stadia+ settings.
