### ISSUE TITLE
DOOM 64 missing from search

### ISSUE THREAD

**Issue by georgeherby** [Mafrans/StadiaPlus#78]
When using the store filter and I enter DOOM 64 no results come up and if I type just DOOM I get just eternal

![image](https://user-images.githubusercontent.com/21989833/82214653-150d3380-990e-11ea-8a3a-3acf9c691324.png)

**Comment by Mafrans** [comment]
This is because StadiaGameDB currently does not include Doom 64 in their database, and the reason the library filter isn't working for Doom 64 users.

There is currently an open issue on the StadiaGameDB github, if StadiaGameDB takes too long to update I may have to write my own database instead.
https://github.com/nilicule/StadiaGameDB/issues/38
