### ISSUE TITLE
2.3.3 doesn't show its UI

### ISSUE THREAD

**Issue by dubigrasu** [Mafrans/StadiaPlus#82]
Basically reporting the same thing I did on discord:

2.3.3 doesn't show up at all in game. In dev console I get:

Error handling response: TypeError: Cannot read property 'classList' of null
    at t.onStart (chrome-extension://bbhmnnecicphphjamhdefpagipoegijd/dist/app.js:1:170248)
    at t.e.load (chrome-extension://bbhmnnecicphphjamhdefpagipoegijd/dist/app.js:1:114181)
    at chrome-extension://bbhmnnecicphphjamhdefpagipoegijd/dist/app.js:1:74417

Can't be sure, but the UI not showing up seems to be related to the "popup fix" changes. If I disable the Popup Fix from the Components, Stadia+ loads and works apparently fine.

Running on Linux, Chromium Version 82. (VA-API Patched)

**Comment by th3bucch** [comment]
Hi there, same here but with the difference that I can't disable any Component because i get this error
`Hey there! This page isn't available yet as the components haven't been loaded. Go to stadia.google.com and log in to enable this feature.` even if I'm into the game.

I'm on chrome-beta v83 running on Linux (Stadia+ v2.3.3), I'm using this extension otherwise the max resolution, I don't know why, is set to 720p.

**Comment by Mafrans** [comment]
Fixed this one myself, didn't want to since I'm on a break but I guess I've gotta make an exception for extension-breaking stuff like this.
